---
- name: Main YAML for RHEL Update Loop
  hosts: "{{ inventory_group }}"
  become: True
  force_handlers: True

  pre_tasks:
    - name: Check host for update status and register current state
      import_tasks: tasks/checkforupdate.yaml
      static: no

  tasks:
    - name: Update output when no work needed
      delegate_to: 127.0.0.1
      copy:
        dest: output/{{ ansible_hostname }}.{{ ansible_date_time.date }}.{{ansible_date_time.epoch}}.appliedupdates.log
        content: "{{ results['results'][0] }}"
        backup: yes
      when: update.rc = 0

    - name: Perform update and go into update loop
      import_tasks: tasks/rhelsysupdate.yaml
      static: no
      when: update.rc > 0
      notify:
      - Loop update

  handlers:
    - name: Loop update
      import_tasks: handlers/rhelsysupdate.yaml
      static: no
      retries: 5
      until: update.rc < 1

  post_tasks:
    - name: Final update check
      import_tasks: tasks/checkforupdate.yaml
      static: no

    - debug:
        var: update.rc
...
