---
- name: Main YAML for RHEL Update Loop
  hosts: "{{ inventory_group }}"
  become: True
  force_handlers: True

  pre_tasks:
    - name: Check host for update status and register current state
      import_tasks: checkforupdate.yaml

  tasks:
    - name: Perform update and go into update loop
      import_tasks: rhelsysupdate_task.yaml
      when: update.rc > 1
      notify:
      - Loop update

  handlers:
    - name: Loop update
      import_tasks: rhelsysupdate_task.yaml
      retries: 5
      until: update.rc < 1

  post_tasks:
    - name: Final update check
      import_tasks: checkforupdate.yaml

    - debug:
        var: update.rc
...
