---
- name: Apply security updates to RHEL system
  hosts: "{{ inventory_group }}"
  become: True
  become_method: sudo
  tasks:
    - name: Apply updates
      yum:
        name: '*'
        state: latest
      register: results

    - name: log results
      copy:
        dest: output/{{ ansible_hostname }}.{{ ansible_date_time.date }}.{{ansible_date_time.epoch}}.appliedupdates.log
        content: "{{ results['results'][0] }}"
        backup: yes
      delegate_to: 127.0.0.1
...
