---
- name: Apply updates
  yum:
    name: '*'
    state: latest
  register: results

- name: log results
  import_tasks: tasks/logresults.yaml
  static: no

- name: update status
  import_tasks: tasks/checkforupdate.yaml
  static: no
...
